apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
  annotations:
    kapp.k14s.io/change-group: "monitoring-app"
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts/
