---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  annotations:
    kapp.k14s.io/change-group: "monitoring-app"
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 56.6.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: kube-prometheus-stack-values
      valuesKey: values.yaml

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: tap-install
spec:
  refreshInterval: 60m

  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: kube-prometheus-stack-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          prometheus:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-production
              hosts:
                - "prometheus.run-prod.cssa.tapsme.org"
              tls:
                - secretName: prometheus-cert
                  hosts:
                    - "prometheus.run-prod.cssa.tapsme.org"
          grafana:
            adminPassword: "{{ .grafanaPassword  }}"
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-production
              hosts:
                - "grafana.run-prod.cssa.tapsme.org"
              tls:
                - secretName: grafana-cert
                  hosts:
                    - "grafana.run-prod.cssa.tapsme.org"
          kube-state-metrics:
            customResourceState:
              enabled: true
              config:
                spec:
                  resources:
                    - groupVersionKind:
                        group: serving.knative.dev
                        version: "v1"
                        kind: Revision
                      labelsFromPath:
                        name: [metadata, name]
                        namespace: [metadata, namespace]
                        workload: [metadata, labels, carto.run/workload-name]
                        knative_service: [metadata, labels, serving.knative.dev/service]
                      metricNamePrefix: knative
                      metrics:
                        - name: revision_status
                          help: Knative Revision status from conditions
                          each:
                            type: Gauge
                            gauge:
                              path: [status, conditions]
                              labelsFromPath:
                                type: ["type"]
                                status: ["status"]
                                reason: ["reason"]
                                message: ["message"]
                                last_transition_time: ["lastTransitionTime"]
                              valueFrom: ["status"]
            rbac:
              extraRules:
                - apiGroups:
                    - sso.apps.tanzu.vmware.com
                  resources:
                    - authservers
                    - clientregistrations
                    - clusterworkloadregistrationclasses
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - ""
                  resources:
                    - configmaps
                    - secrets
                    - nodes
                    - pods
                    - services
                    - serviceaccounts
                    - resourcequotas
                    - replicationcontrollers
                    - limitranges
                    - persistentvolumeclaims
                    - persistentvolumes
                    - namespaces
                    - endpoints
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - apps
                  resources:
                    - statefulsets
                    - daemonsets
                    - deployments
                    - replicasets
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - pkg.crossplane.io
                  resources:
                    - providers
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - kubernetes.crossplane.io
                  resources:
                    - objects
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - batch
                  resources:
                    - cronjobs
                    - jobs
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - autoscaling
                  resources:
                    - horizontalpodautoscalers
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - authentication.k8s.io
                  resources:
                    - tokenreviews
                  verbs:
                    - create
                - apiGroups:
                    - authorization.k8s.io
                  resources:
                    - subjectaccessreviews
                  verbs:
                    - create
                - apiGroups:
                    - policy
                  resources:
                    - poddisruptionbudgets
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - certificates.k8s.io
                  resources:
                    - certificatesigningrequests
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - discovery.k8s.io
                  resources:
                    - endpointslices
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - storage.k8s.io
                  resources:
                    - storageclasses
                    - volumeattachments
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - admissionregistration.k8s.io
                  resources:
                    - mutatingwebhookconfigurations
                    - validatingwebhookconfigurations
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - networking.k8s.io
                  resources:
                    - networkpolicies
                    - ingressclasses
                    - ingresses
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - coordination.k8s.io
                  resources:
                    - leases
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - rbac.authorization.k8s.io
                  resources:
                    - clusterrolebindings
                    - clusterroles
                    - rolebindings
                    - roles
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - carto.run
                  resources:
                    - deliverables
                    - workloads
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - conventions.carto.run
                  resources:
                    - podintents
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - source.toolkit.fluxcd.io
                  resources:
                    - gitrepositories
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - source.apps.tanzu.vmware.com
                  resources:
                    - imagerepositories
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - tekton.dev
                  resources:
                    - taskruns
                    - pipelineruns
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - scanning.apps.tanzu.vmware.com
                  resources:
                    - imagescans
                    - sourcescans
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - kpack.io
                  resources:
                    - images
                    - builds
                    - clusterbuilders
                    - clusterbuildpacks
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - packaging.carvel.dev
                  resources:
                    - packagerepositories
                    - packageinstalls
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - kappctrl.k14s.io
                  resources:
                    - apps
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - serving.knative.dev
                  resources:
                    - services
                    - revisions
                    - configurations
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - eventing.knative.dev
                  resources:
                    - triggers
                    - brokers
                    - rabbitmqbrokerconfigs
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - servicebinding.io
                  resources:
                    - servicebindings
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - services.apps.tanzu.vmware.com
                  resources:
                    - clusterinstanceclasses
                    - classclaims
                    - resourceclaims
                    - resourceclaimpolicies
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - apis.apps.tanzu.vmware.com
                  resources:
                    - apidescriptors
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - accelerator.apps.tanzu.vmware.com
                  resources:
                    - accelerators
                    - fragments
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - apiextensions.k8s.io
                  resources:
                    - customresourcedefinitions
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - bitnami.messaging.tanzu.vmware.com
                  resources:
                    - xrabbitmqclusters
                    - xkafkainstances
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - bitnami.database.tanzu.vmware.com
                  resources:
                    - xmysqlinstances
                    - xpostgresqlinstances
                    - xmongodbinstances
                  verbs:
                    - list
                    - watch
                - apiGroups:
                    - bitnami.caching.tanzu.vmware.com
                  resources:
                    - xredisclusters
                  verbs:
                    - list
                    - watch
  data:
    - secretKey: grafanaPassword
      remoteRef:
        key: grafanaPassword
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: kube-prometheus-stack-values
  namespace: tap-install
spec:
  toNamespaces:
    - monitoring
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  fromNamespace: tap-install