apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kapp.k14s.io/change-group: "monitoring-deps"
    kapp.k14s.io/disable-default-ownership-label-rules: ""
    kapp.k14s.io/change-rule.delete-order-0: "delete after deleting monitoring-app"
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "effect":"NoSchedule", "key": "CriticalAddonsOnly", "value": "true"}]'
