apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-pipelines
  namespace: tap-install
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.99: tap-scale-overlays
spec:
  packageRef:
    refName: tekton.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.50.3+tanzu.4"
  serviceAccountName: tap-install-sa