apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/disable-wait: ""
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install-azure
      ref: origin/main
      subPath: build-packaging
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
          overlay-tap-package.yml: |
            #@ load("@ytt:overlay", "overlay")
        
            #@ def with_name(vlan):
            ytt:
              #@overlay/match missing_ok=True
              inline:
                pathsFrom:
                  - secretRef:
                      name: tap-pkg-overlay-secret
            #@ end
            
            #@overlay/match by=overlay.subset({"kind":"Package","metadata":{"namespace":"tap-install"}}),expects="1+"
            ---
            spec:
              template:
                spec:
                  template:
                    #@overlay/match by=lambda idx, left, right: "ytt" in left, expects="1+"
                    #@overlay/replace via=lambda left, right: overlay.apply(left, with_name(left))
  deploy:
  - kapp:
      rawOptions:
      - --diff-changes=true