apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/disable-wait: ""
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install-azure
      ref: origin/main
      subPath: build-packaging
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            label_propagation_exclusions: ["kapp.k14s.io/app", "kapp.k14s.io/association"]
  deploy:
  - kapp:
      rawOptions:
      - --diff-changes=true