apiVersion: v1
kind: Secret
metadata:
  name: tap-scale-values
  namespace: tap-install
stringData:
  scale-values.yaml: |
    contour:
      envoy:
        workload:
          type: Deployment
          replicas: 3
    
    tap_telemetry:
      limit_memory: 2Gi