apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-xplane
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: azure-xplane
    creationPolicy: Owner

  data:
  - secretKey: azurexplane
    remoteRef:
      key: azurexplane
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: azure-xplane
  namespace: tap-install
spec:
  toNamespaces:
  - crossplane-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: azure-xplane
  namespace: crossplane-system
spec:
  fromNamespace: tap-install