apiVersion: v1
kind: Secret
metadata:
  name: workload-git-ssh-overlay
  namespace: tap-install
stringData:
  workload-git-auth-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount","metadata":{"name":"default"}}), expects="0+"
    ---
    secrets:
      #@overlay/append
      - name: git-auth