#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: full-tbs-deps-values
  namespace: tap-install
stringData:
  values.yaml: |
    kp_default_repository: "cxscssa.azurecr.io/tanzu-build-service-full-deps/full-deps-package-repo"