---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: full-tbs-deps
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  serviceAccountName: tap-tap-install-sa
  packageRef:
    refName: full-deps.buildservice.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.7.29"
      prereleases: {}
  values:
    - secretRef:
        name: full-tbs-deps-values