apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lsp-credentials
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: lsp-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .tempregistry | toString }}"

  data:
  - secretKey: tempregistry
    remoteRef:
      key: tempregistry