apiVersion: v1
kind: Secret
metadata:
  name: remove-tbsdepsupdater-overlay
  namespace: tap-install
type: Opaque
stringData:
  remove-tbsdepsupdater-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "TanzuNetDependencyUpdater","metadata":{"name":"dependency-updater","namespace":"build-service"}}), expects="0+"
    ---
    #@overlay/remove