apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-rbac-overlay
  namespace: tap-install
type: Opaque
stringData:
  tap-gui-rbac-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ClusterRole","metadata":{"name":"k8s-reader"}})
    ---
    rules:
    #@overlay/append
    - apiGroups: ['apiextensions.k8s.io']
      resources: ['customresourcedefinitions']
      verbs: ['get', 'watch', 'list']
         