apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-values
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: full
          ceip_policy_disclosed: true

          shared:
            ingress_domain: full.cssa.tapsme.org
            ingress_issuer: letsencrypt-production

          supply_chain: testing_scanning

          ootb_supply_chain_basic:
            registry:
              server: "registry.harbor.learn.tapsme.org"
              repository: "tap-workloads" 

          ootb_supply_chain_testing:
            registry:
              server: "registry.harbor.learn.tapsme.org"
              repository: "tap-workloads" 

          ootb_supply_chain_testing_scanning:
            registry:
              server: "registry.harbor.learn.tapsme.org"
              repository: "tap-workloads" 

          buildservice:
            exclude_dependencies: true
            pull_from_kp_default_repo: true
            kp_default_repository: "registry.harbor.learn.tapsme.org/tap-build-service/full-tbs-deps"
            kp_default_repository_secret:
              namespace: tap-install
              name: registry-credentials

          local_source_proxy:
            repository: "registry.harbor.learn.tapsme.org/tap-workloads/local-source"

            push_secret:
              name: lsp-credentials
              namespace: tap-install
              create_export: true

          metadata_store:
            ns_for_export_app_cert: "demo"
            app_service_type: ClusterIP

          scanning:
            metadataStore:
              url: ""


          contour:
            envoy:
              service:
                type: LoadBalancer   

          tap_gui:
            service_type: ClusterIP
            app_config:
              auth:
                allowGuestAccess: true
              organization:
                name: "CSSA Team"
              catalog:
                locations:
                  - type: url
                    target: https://github.com/maelarge/tap-catalog/blob/main/catalog-info.yaml                  

          crossplane:
            orphan_resources: false

          cnrs:
            domain_template: '{{"{{"}}.Name{{"}}"}}-{{"{{"}}.Namespace{{"}}"}}.{{"{{"}}.Domain{{"}}"}}'
          
          namespace_provisioner:
            controller: true
            additional_sources:
            - git:
                url: ssh://git@github.com/Mpluya/tap-namespaces-azure
                ref: origin/main
                subPath: credentials
                secretRef:
                  name: tap-install-gitops-ssh 
                  namespace: tap-install
              path: _ytt_lib/custom-resources-creds
            - git:
                url: ssh://git@github.com/Mpluya/tap-namespaces-azure
                ref: origin/main
                subPath: additional-resources-build
                secretRef:
                  name: tap-install-gitops-ssh-too
                  namespace: tap-install
                  create_export: true
              path: _ytt_lib/custom-resources-build
            parameter_prefixes:
            - tap.tanzu.vmware.com              
            import_data_values_secrets:
            - name: tenant-secrets
              namespace: tap-install
              create_export: true
            overlay_secrets:
            - name: workload-git-ssh-overlay
              namespace: tap-install
              create_export: true
  data:
  - secretKey: tapregistrypassword
    remoteRef:
      key: tapregistrypassword