apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values
  namespace: tap-install
spec:
  refreshInterval: 0m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-values
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: full
          ceip_policy_disclosed: true

          shared:
            ingress_domain: full.cssa.tapsme.org
            ingress_issuer: letsencrypt-production
            image_registry:  
              username: "robot$unicorn-robot"
              password: "{{ .tapregistrypassword}}"

          supply_chain: basic

          ootb_supply_chain_basic:
            registry:
              server: "registry.harbor.learn.tapsme.org"
              repository: "tap-workloads" 

          buildservice:
            exclude_dependencies: true
            kp_default_repository: "registry.harbor.learn.tapsme.org/tap-build-service"

          contour:
            envoy:
              service:
                type: LoadBalancer   

          tap_gui:
            service_type: ClusterIP
            app_config:
              organization:
                name: "CSSA Team"
              catalog:
                locations:
                  - type: url
                    target: https://github.com/maelarge/tap-catalog/blob/main/catalog-info.yaml                  

  data:
  - secretKey: tapregistrypassword
    remoteRef:
      key: tapregistrypassword