apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kapp.k14s.io/change-group: pkgr
  name: tbs-full-deps-repository 
  namespace: tap-install
spec:
  paused: true
  fetch:
    imgpkgBundle:
      image: registry.harbor.learn.tapsme.org/tap-build-service/full-tbs-deps:1.7.0-rc.10
      secretRef: 
        name: tap-registry
        namespace: tap-install