apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: post-pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
    packaging.carvel.dev/downgradable: ""
  name: full-tbs-deps
  namespace: tap-install
spec:
  packageRef:
    refName: full-tbs-deps.tanzu.vmware.com
    versionSelection:
      constraints: ">1.0.0"
      prereleases: {}
  serviceAccountName: tap-tap-install-sa
