apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-secrets
  namespace: tap-install
spec:
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store
  refreshInterval: "0m"
  target:
    name: tenant-secrets
    creationPolicy: Owner
    template:
      data:
        known_hosts: "{{ .githubsshknownhosts }}"
        identity: "{{ .githubsshprivatekey }}"
        ssh-privatekey: "{{ .githubsshprivatekey }}"
        identity.pub: "{{ .githubsshpublickey }}"

  data:
  - secretKey: githubsshknownhosts
    remoteRef:
      key: githubsshknownhosts
  - secretKey: githubsshprivatekey
    remoteRef:
      key: githubsshprivatekey
  - secretKey: githubsshpublickey
    remoteRef:
      key: githubsshpublickey