apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-secrets
  namespace: tap-install
spec:
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store
  refreshInterval: "0m"
  target:
    name: tenant-secrets
    creationPolicy: Owner
    template:
      data: 
        content.yaml: |
          known_hosts: "{{ .githubsshknownhostsstring }}"
          identity: "{{ .githubsshprivatekeystring }}"
          ssh_privatekey: "{{ .githubsshprivatekeystring }}"
          identity_pub: "{{ .githubsshpublickey }}"

  data:
  - secretKey: githubsshknownhostsstring
    remoteRef:
      key: githubsshknownhostsstring
  - secretKey: githubsshprivatekeystring
    remoteRef:
      key: githubsshprivatekeystring
  - secretKey: githubsshpublickey
    remoteRef:
      key: githubsshpublickey
