apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-secret-store
  namespace: tap-install
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://tap-eso-vault.vault.azure.net"
      serviceAccountRef:
        name: eso