apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-credentials
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: test-credentials
    creationPolicy: Owner
  data:
  - secretKey: example-externalsecret-key
    remoteRef:
      key: example-externalsecret-key  