#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: ootb-basic-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.ootb_supplychain_basic_install)
