apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    packaging.carvel.dev/package-ClusterRole: managed-resource-controller-tap-install-cluster-role
    packaging.carvel.dev/package-ClusterRoleBinding: managed-resource-controller-tap-install-cluster-rolebinding
    packaging.carvel.dev/package-ServiceAccount: tap-tap-install-sa
  name: managed-resource-controller
  namespace: tap-install
spec:
  packageRef:
    refName: managed-resource-controller.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.1.2
      prereleases: {}
  serviceAccountName: tap-tap-install-sa