#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-supply-chain-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.helm_supply_chain_install)
