apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kapp-experiments-app
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
    - git:
        url: ssh://git@github.com/Mpluya/kapp-ownership-experiment
        ref: origin/main
        secretRef:
          name: tap-install-gitops-ssh
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions:
          - --diff-changes=true
          - --dangerous-override-ownership-of-existing-resources=true