---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: cert-manager
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: cert-manager
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: tap-gui
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: tap-gui
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: metadata-store
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: metadata-store
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: api-portal
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: api-portal
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: api-auto-registration
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: api-auto-registration
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: demo
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: demo
imagePullSecrets:
  - name: tap-registry
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
  namespace: mae
spec:
  fromNamespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: mae
imagePullSecrets:
  - name: tap-registry
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: certificate-notices@cool.com
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: contour
            podTemplate:
              spec:
                serviceAccountName: tap-acme-http01-solver