apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rando-app
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  fetch:
    - git:
        url: https://github.com/Mpluya/repo-with-large-file-storage.git
        ref: origin/master
        secretRef:
          name: git-credentials
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions:
          - --dangerous-allow-empty-list-of-resources=true