---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu:amr:observer:editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu:amr:observer:edit
subjects:
  - kind: ServiceAccount
    name: amr-observer-editor
    namespace: amr-observer-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu:amr:observer:edit
rules:
  - apiGroups: ["cloudevents.amr.apps.tanzu.vmware.com"]
    resources: ["*"]
    verbs: ["update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amr-observer-editor
  namespace: amr-observer-system
  annotations:
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amr-observer-edit-token
  namespace: tap-install
spec:
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      data:
        token: "{{ .cehEditToken | b64dec }}"
  data:
  - secretKey: cehEditToken
    remoteRef:
      key: cehEditToken
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: amr-observer-edit-token
  namespace: tap-install
spec:
  toNamespaces: 
    - amr-observer-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: amr-observer-edit-token
  namespace: amr-observer-system
spec:
  fromNamespace: tap-install
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amr-observer-editor-token
  namespace: tap-install
spec:
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      metadata:
        annotations:
          kubernetes.io/service-account.name: amr-observer
      data:
        ca.crt: "{{ .amrcloudeventhandlercacrt | b64dec }}"
        token: "{{ .amrcloudeventhandleredittoken | b64dec }}"
  data:
  - secretKey: amrcloudeventhandlercacrt
    remoteRef:
      key: amrcloudeventhandlercacrt
  - secretKey: amrcloudeventhandleredittoken
    remoteRef:
      key: amrcloudeventhandleredittoken
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: amr-observer-editor-token
  namespace: tap-install
spec:
  toNamespaces: 
    - amr-observer-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: amr-observer-editor-token
  namespace: amr-observer-system
spec:
  fromNamespace: tap-install