apiVersion: v1 
kind: Secret
metadata: 
  name: convention-template-overlay
  namespace: tap-install
stringData:
  convention-template-overlay.yaml: | 
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")

    #@ def convention_template(): 
    kind: ClusterConfigTemplate 
    metadata:
      name: convention-template
    #@ end

    #@overlay/match by=overlay.subset(convention_template())
    ---
    spec:
      #@overlay/replace via=lambda left, right: left + right
      ytt: "\n      topologySpreadConstraints:\n      - maxSkew: 1\n        wheneUnsatisfiable: \"ScheduleAnyway\" \n        topologykey: \"topology.kubernetes.io/zone\""

