apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-key
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: cosign-key
    creationPolicy: Owner

  data:
  - secretKey: cosign
    remoteRef:
      key: key/cosign
