apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-basic-auth
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: gitops-basic-auth
    creationPolicy: Owner
    template:
      data:
        password: "{{ .gitPassword }}"
        username: "{{ .gitUsername }}"
        host: https://github.com
  data:
  - secretKey: gitPassword
    remoteRef:
      key: gitPassword
  - secretKey: gitUsername
    remoteRef:
      key: gitUsername
  - secretKey: githubsshpublickey
    remoteRef:
      key: githubsshpublickey