apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: git-credentials
    creationPolicy: Owner
    template:
      type: git-credentials
      data:
        type: git-credentials
        password: "{{ .gitPassword }}"
        username: "{{ .gitUsername }}"
        url: https://github.com
  data:
  - secretKey: gitPassword
    remoteRef:
      key: gitPassword
  - secretKey: gitUsername
    remoteRef:
      key: gitUsername
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-credentials
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-credentials
  namespace: demo
spec:
  fromNamespace: tap-install