apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-store
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: oci-store
    creationPolicy: Owner
    template:
      data:
        username: "cxscssa"
        password: "{{ .tapregistrypassword }}"
        server: "cxscssa.azurecr.io"
        repository: "tap-build/workloads"
  data:
    - secretKey: tapregistrypassword
      remoteRef:
        key: tapregistrypassword
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: oci-store
  namespace: tap-install
spec:
  toNamespaces:
    - '*'