---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: ootb-supply-chain-basic
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ootb-supply-chain-overlay
spec:
  serviceAccountName: tap-tap-install-sa
  packageRef:
    refName: ootb-supply-chain-basic.tanzu.vmware.com
    versionSelection:
      constraints: 0.13.6
  values:
    - secretRef:
        name: ootb-basic-values