apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-supply-chain-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
    
    #@ basic_sc = overlay.subset({"kind": "ClusterSupplyChain", "name":"source-to-url"})
    #@ testing_scanning_sc = overlay.subset({"kind": "ClusterSupplyChain", "name":"source-test-scan-to-url"})
    
    #@overlay/match by=overlay.or_op(testing_scanning_sc, basic_sc), expects="0+"
    ---
    spec:
      params:
      #@overlay/append
      - name: deliverable_repository_owner
        default: "Mpluya"
      - name: deliverable_repository_name
        default: "tap-azure-deliverable-config-repo"
      - name: deliverable_branch
        default: main


    #@overlay/match by=testing_scanning_sc, expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by=overlay.index(2)
      #@overlay/insert before=True
      - name: source-scanner
        params:
        - default: scan-policy
          name: scanning_source_policy
        - default: blob-source-scan-template
          name: scanning_source_template
        sources:
        - name: source
          resource: source-tester
        templateRef:
          kind: ClusterSourceTemplate
          name: source-scanner-template

    #@overlay/match by=overlay.or_op(testing_scanning_sc, basic_sc), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/remove
      - name: deliverable

    #@overlay/match by=overlay.or_op(testing_scanning_sc, basic_sc), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: config-writer
      #@overlay/append
      - name: create-deliverable
        configs:
          - resource: config-writer
            name: config   
        templateRef:
          kind: ClusterConfigTemplate
          name: config-deliverable-template  
      - name: write-deliverable
        configs:
        - name: config
          resource: create-deliverable   
        params:
        - name: serviceAccount
          value: default
        templateRef:
          kind: ClusterTemplate
          name: config-writer-deliverable-template


    #@overlay/match by=overlay.or_op(testing_scanning_sc, basic_sc), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: config-writer
        #@overlay/replace
        templateRef:
          kind: ClusterConfigTemplate
          name: config-writer-template
          
         