apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-supply-chain-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
    
    #@ basic = overlay.subset({"kind": "ClusterSupplyChain", "metadata":{"name":"source-to-url"}})
    #@ imagebasic = overlay.subset({"kind": "ClusterSupplyChain", "metadata":{"name":"basic-image-to-url"}})
    #@ testingscanning = overlay.subset({"kind": "ClusterSupplyChain", "metadata":{"name":"source-test-scan-to-url"}})
    #@ imagetestingscanning = overlay.subset({"kind": "ClusterSupplyChain", "metadata":{"name":"scanning-image-scan-to-url"}})
    
    #@overlay/match by=overlay.or_op(testingscanning, basic), expects="0+"
    ---
    spec:
      params:
      #@overlay/append
      - name: deliverable_repository_owner
        default: "Mpluya"
      - name: deliverable_repository_name
        default: "tap-azure-deliverable-config-repo"
      - name: deliverable_branch
        default: main


    #@overlay/match by=overlay.or_op(testingscanning, basic), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/remove
      - name: deliverable

    #@overlay/match by=overlay.or_op(testingscanning, basic), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: api-descriptors
      #@overlay/append
      - name: create-deliverable
        configs:
          - resource: api-descriptors
            name: config   
        templateRef:
          kind: ClusterConfigTemplate
          name: config-deliverable-template  
      - name: write-deliverable
        configs:
        - name: config
          resource: create-deliverable   
        params:
        - name: serviceAccount
          value: default
        templateRef:
          kind: ClusterTemplate
          name: config-writer-deliverable-template
          
         