apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-supply-chain-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
        
    #@overlay/match by=overlay.subset({"kind":"ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      params:
      #@overlay/append
      - name: deliverable_repository_owner
        default: "Mpluya"
      - name: deliverable_repository_name
        default: "tap-azure-workload-config-repo"
      - name: deliverable_branch
        default: main


    #@overlay/match by=overlay.subset({"apiVersion": "carto.run/v1alpha1", "kind": "ClusterSupplyChain","metadata":{"name":"source-test-scan-to-url"}}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/remove
      - name: deliverable

    #@overlay/match by=overlay.subset({"kind":"ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: config-writer
      #@overlay/append
      - name: deliverable-config
        configs:
          - resource: config-writer
            name: config   
        templateRef:
          kind: ClusterConfigTemplate
          name: config-deliverable-template  
      - name: deliverable-config-writer
        configs:
        - name: config
          resource: deliverable-config    
        params:
        - name: serviceAccount
          value: default
        templateRef:
          kind: ClusterTemplate
          name: config-writer-deliverable-template


    #@overlay/match by=overlay.subset({"kind":"ClusterSupplyChain"}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      - name: config-writer
        #@overlay/replace
        templateRef:
          kind: ClusterConfigTemplate
          name: config-writer-template
          
         