apiVersion: v1
kind: Secret
metadata:
  name: ootb-template-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-template-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:regexp", "regexp")
    #@ load("@ytt:data", "data")

    #@ def replace_expr(old, _):
    #@   new = regexp.replace("(?m)value: #@ \"config/.*", old, "value: #@ \"config/\" + data.values.workload.metadata.namespace + \"/\" + data.values.workload.metadata.name + \"/dev" + "\"")
    #@   return new
    #@ end

    #@overlay/match by=overlay.subset({"kind": "ClusterTemplate","metadata":{"name":"config-writer-template"}}), expects="0+"
    ---
    spec:
      #@overlay/replace via=lambda left,right: replace_expr(left,right)
      ytt:


    #@overlay/match by=overlay.subset({"kind": "ClusterTemplate","metadata":{"name":"config-writer-template"}}), expects="0+"
    ---
    #@overlay/replace
    kind: ClusterConfigTemplate
    spec:
      #@overlay/match missing_ok=True
      configPath: .status.completionTime