apiVersion: v1
kind: Secret
metadata:
  name: ootb-template-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-template-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "ClusterTemplate","metadata":{"name":"config-writer-template"}}), expects="0+"
    ---
    #@overlay/replace
    kind: ClusterConfigTemplate
    spec:
      #@overlay/match missing_ok=True
      configPath: .spec.inputs.params