apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-post-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install-azure
      ref: origin/main
      subPath: build-packaging-post-install
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          overlay-tap-pkgi.yml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"kind":"PackageInstall","metadata":{"namespace":"tap-install"}}),expects="1+"
            ---
            metadata:
              #@overlay/match missing_ok=True
              annotations:
                #@overlay/match missing_ok=True
                ext.packaging.carvel.dev/ytt-paths-from-secret-name.99: tap-namespaces-overlay-secret
  deploy:
  - kapp:
      rawOptions:
      - --diff-changes=true
      - --wait=false