apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tanzu-registry
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tanzu-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .tanzuregistry | toString }}"

  data:
  - secretKey: tapregistry
    remoteRef:
      key: tapregistry