apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-registry-basic-auth
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-registry-basic-auth
    creationPolicy: Owner
    template:
      data:
        username: "cxscssa"
        password: "{{ .tapregistrypassword }}"

  data:
    - secretKey: tapregistrypassword
      remoteRef:
        key: tapregistrypassword