apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-gitops-ssh
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tenant-gitops-ssh
    creationPolicy: Owner
    template:
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          tekton.dev/git-0: github.com
      data:
        known_hosts: "{{ .githubsshknownhosts }}"
        identity: "{{ .githubsshprivatekey }}"
        ssh-privatekey: "{{ .githubsshprivatekey }}"
        identity.pub: "{{ .githubsshpublickey }}"

  data:
  - secretKey: githubsshknownhosts
    remoteRef:
      key: githubsshknownhosts
  - secretKey: githubsshprivatekey
    remoteRef:
      key: githubsshprivatekey
  - secretKey: githubsshpublickey
    remoteRef:
      key: githubsshpublickey