apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: helm-controller
  namespace: tap-install
spec:
  packageRef:
    refName: fluxcd-helm-controller.tanzu.vmware.com
    versionSelection:
      constraints: 0.36.2+vmware.1-tkg.1
  serviceAccountName: tap-installer-sa
  values:
    - secretRef:
        name: helm-controller-values
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-controller-values
  namespace: tap-install
stringData:
  values.yaml: |
    namespace: tanzu-helm-controller