apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: contour-pods
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: contour
  namespaceSelector:
    matchNames:
      - tanzu-system-ingress
  podMetricsEndpoints:
    - port: "8000"
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-pods
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: envoy
  namespaceSelector:
    matchNames:
      - tanzu-system-ingress
  podMetricsEndpoints:
    - port: "8002"
      path: /stats/prometheus