#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: test-and-notify-pipelinerun
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
    revision: spec.params[?(@.name=="source-revision")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      pipelineRef:
        name: $(selected.metadata.name)$
      params: $(runnable.spec.inputs.tekton-params)$
