---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: friday-sre-app
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref: origin/main
      secretRef: 
        name: tap-install-gitops-ssh
      subPath: packages/friday-sre-package.bobbyhana.cssa.vmware.com/packages
  - git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref: origin/main
      secretRef: 
        name: tap-install-gitops-ssh-too
      subPath: packages/friday-sre-package.bobbyhana.cssa.vmware.com/prod
  template:
  - ytt: {}
  
  deploy:
  - kapp:
      intoNs: bobbyhana
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]