apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: components.supplychains.pve.tanzu.vmware.com
  namespace: supplychains
  annotations:
    kapp.k14s.io/change-group: "tanzu-supplychain-components"
spec:
  serviceAccountName: tanzu-supplychain-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/myfirstsupplychaingroup.git
      ref: origin/main
      subPath: components
      secretRef: 
        name: tap-install-gitops-ssh
  - git:
      url: ssh://git@github.com/Mpluya/myfirstsupplychaingroup.git
      ref: origin/main
      subPath: pipelines
      secretRef:
        name: tap-install-gitops-ssh
  - git:
      url: ssh://git@github.com/Mpluya/myfirstsupplychaingroup.git
      ref: origin/main
      subPath: tasks
      secretRef:
        name: tap-install-gitops-ssh
  template:
  - ytt: {}

  deploy:
  - kapp:
      rawOptions:
      - --dangerous-allow-empty-list-of-resources=true
      - --diff-changes=true