apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values
  namespace: tap-install
spec:
  refreshInterval: 0m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-values
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: view
          ceip_policy_disclosed: true

          shared:
            ingress_domain: view.cssa.tapsme.org
            ingress_issuer: letsencrypt-production

          contour:
            infrastructure_provider: azure
            envoy:
              service:
                type: LoadBalancer

          tap_gui:
            metadataStoreAutoconfiguration: true
            service_type: ClusterIP
            app_config:
              organization:
                name: "CSSA Team"
              catalog:
                locations:
                  - type: url
                    target: https://github.com/maelarge/tap-catalog/blob/main/catalog-info.yaml                  
              auth:
                environment: development
                providers:
                  github:
                    development:
                      clientId: 08cfa793c9fc0417343b
                      clientSecret: {{ .githubclientsecret }}

              integrations:
                github:
                  - host: github.com
                    token: {{ .githubtoken }}

          appliveview:
            ingressEnabled: true
            ingress_issuer: letsencrypt-production

          accelerator:
            ingress:
              include: true

          metadata_store:
            ingress_enabled: "true"
            app_service_type: "ClusterIP"
            ns_for_export_app_cert: "*"          

          excluded_packages:
          - learningcenter.tanzu.vmware.com
          - workshops.learningcenter.tanzu.vmware.com

  data:
  - secretKey: githubclientsecret
    remoteRef:
      key: githubclientsecret
  - secretKey: githubtoken
    remoteRef:
      key: githubtoken
