apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: azure-postgres
spec:
  description:
    short: Azure Postgresql database instances
  provisioner:
    crossplane:
      compositeResourceDefinition: xpostgresqlinstances.bindable.database.example.org