---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-pkg-and-pkgi-install-sa
  namespace: kustomize-fun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kustomize-fun
  name: app-pkg-and-pkgi-install-role
rules:
  - apiGroups: ["data.packaging.carvel.dev"]
    resources: ["packages"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["packaging.carvel.dev"]
    resources: ["packageinstalls"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-pkg-and-pkgi-install-rb
  namespace: kustomize-fun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-pkg-and-pkgi-install-role
subjects:
  - kind: ServiceAccount
    name: app-pkg-and-pkgi-install-sa
    namespace: namespace
