---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    packaging.carvel.dev/package: trivy-scanning-component-tap-install
    tkg.tanzu.vmware.com/tanzu-package: trivy-scanning-component-tap-install
  creationTimestamp: null
  name: trivy-scanning-component-tap-install-sa
  namespace: tap-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    packaging.carvel.dev/package: trivy-scanning-component-tap-install
    tkg.tanzu.vmware.com/tanzu-package: trivy-scanning-component-tap-install
  creationTimestamp: null
  name: trivy-scanning-component-tap-install-cluster-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    packaging.carvel.dev/package: trivy-scanning-component-tap-install
    tkg.tanzu.vmware.com/tanzu-package: trivy-scanning-component-tap-install
  creationTimestamp: null
  name: trivy-scanning-component-tap-install-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-scanning-component-tap-install-cluster-role
subjects:
  - kind: ServiceAccount
    name: trivy-scanning-component-tap-install-sa
    namespace: tap-install
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    packaging.carvel.dev/package-ClusterRole: trivy-scanning-component-tap-install-cluster-role
    packaging.carvel.dev/package-ClusterRoleBinding: trivy-scanning-component-tap-install-cluster-rolebinding
    packaging.carvel.dev/package-ServiceAccount: trivy-scanning-component-tap-install-sa
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: trivy-scanning-component-tap-install-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: trivy-scanning-component-tap-install-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: trivy-scanning-component-tap-install-sa
  creationTimestamp: null
  name: trivy-scanning-component
  namespace: tap-install
spec:
  packageRef:
    refName: trivy.app-scanning.component.apps.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.2.0-alpha"
      prereleases: {}
  serviceAccountName: trivy-scanning-component-tap-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0