apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: opencost
  namespace: opencost
spec:
  virtualhost:
    fqdn: opencost.view.cssa.tapsme.org
    tls:
      secretName: opencost
    routes:
    - conditions:
      - prefix: /
      services:
        - name: opencost
          port: 9003
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opencost
  namespace: opencost
spec:
  dnsNames:
  - opencost.view.cssa.tapsme.org 
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: opencost
  usages:
  - digital signature
  - key encipherment