apiVersion: v1
kind: Secret
metadata:
  name: tap-scale-values
  namespace: tap-install
stringData:
  scale-values.yaml: |
    contour:
      envoy:
        workload:
          type: Deployment
          replicas: 3
    
    buildservice:
      controller:
        resources:
          limits:
            memory: 2Gi
            cpu: 100m
          requests:
            memory: 1Gi
            cpu: 20m
    
    app_scanning:
      scans:
        maxConcurrentScans: 50
    
    scanning:
      resources:
        limits:
          cpu: 500m
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 1Gi

    tap_telemetry:
      limit_memory: 2Gi

    amr:
      observer:
        app_limit_cpu: 500m
        app_limit_memory: 1Gi
        app_req_cpu: 100m
        app_req_memory: 256Mi
    
    cartographer_conventions:
      resources:
        limits:
          memory: 1.8Gi
    
    cartographer:
      cartographer:
        concurrency:
          max_workloads: 50
          max_deliveries: 50
          max_runnables: 50
        # build server settings
        resources: 
          limits:
            cpu: 4
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
        # run cluster settings below
     #  resources:
     #    limits:
     #      cpu: 4
     #      memory: 2Gi
     #    requests:
     #      cpu: 3
     #      memory: 1G

    # only valid when controller: true
    #namespace_provisioner:
    #  controller_resources:
    #    resources:
    #      limits:
    #        cpu: 500m
    #        memory: 2Gi
    #      requests:
    #        cpu: 100m
    #        memory: 500Mi