apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tbs-dependencies-package-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: tanzu-build.packages.broadcom.com/build-service-dependency-updater/package-repo
      secretRef:
        name: tanzu-build-broadcom-artifactory
      tagSelection:
        semver:
          constraints: 1.11.x