---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-supplychain-sa
  namespace: bobbyhana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-supplychain-cluster-rolebinding-bobbyhana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-supplychain-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-supplychain-sa
    namespace: bobbyhana