apiVersion: v1
kind: Secret
metadata:
  name: tekton-source-pipeline-run-template-overlay
  namespace: tap-install
stringData:
  tekton-source-pipeline-run-template-overlay.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    
    #@overlay/match by=overlay.subset({"kind": "ClusterRunTemplate", "metadata": {"name": "tekton-source-pipelinerun"}}), expects="0+"
    ---
    spec:
      template:
        spec:
          #@overlay/match missing_ok=True
          #@overlay/match-child-defaults missing_ok=True
          taskRunSpecs:
          - pipelineTaskName: test
            computeResources:
              requests:
                cpu: 1.5
                memory: 1000Mi
              limits:
                cpu: 3
                memory: 2500Mi