apiVersion: v1
kind: Secret
metadata:
  name: tap-scale-values
  namespace: tap-install
stringData:
  scale-values.yaml: |
    contour:
      envoy:
        workload:
          type: Deployment
          replicas: 3
    
    appliveview_connector:
      connector:
        deployment:
          enabled: true
          replicas: 2
    
      cnrs:
        resource_management:
          - name: "controller"
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          - name: "net-contour-controller"
            limits:
              cpu: 400m
              memory: 2Gi
            requests:
              cpu: 40m
              memory: 512Mi
          - name: "autoscaler"
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
          - name: "activator"
            limits:
              cpu: 1000m
              memory: 5Gi
            requests:
              cpu: 300m
              memory: 5Gi
    
    tap_telemetry:
      limit_memory: 2Gi

    amr:
      observer:
        app_limit_cpu: 500m
        app_limit_memory: 1Gi
        app_req_cpu: 100m
        app_req_memory: 256Mi
    
    cartographer:
      cartographer:
        concurrency:
          max_workloads: 50
          max_deliveries: 50
          max_runnables: 50
        # run cluster settings below
         resources:
           limits:
             cpu: 4
             memory: 2Gi
           requests:
             cpu: 3
             memory: 1G

    # only valid when controller: true
    #namespace_provisioner:
    #  controller_resources:
    #    resources:
    #      limits:
    #        cpu: 500m
    #        memory: 2Gi
    #      requests:
    #        cpu: 100m
    #        memory: 500Mi