apiVersion: v1
kind: Secret
metadata:
  name: tap-scale-overlays
  namespace: tap-install
stringData:
  fluxcd-source-overlay.yaml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"fluxcd-source-controller", "namespace": "flux-system"}}), expects="0+"
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: manager
            resources:
              limits:
                cpu: "4"
                memory: "4Gi"
              requests:
                cpu: "2"
                memory: "2Gi"
            args:
            - --concurrent=30
            - --requeue-dependency=5s
  tekton-source-pipeline-run-template-overlay.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    
    #@overlay/match by=overlay.subset({"kind": "ClusterRunTemplate", "metadata": {"name": "tekton-source-pipelinerun"}}), expects="0+"
    ---
    spec:
      template:
        spec:
          #@overlay/match missing_ok=True
          #@overlay/match-child-defaults missing_ok=True
          taskRunSpecs:
          - pipelineTaskName: test
            computeResources:
              requests:
                cpu: 1.5
                memory: 1000Mi
              limits:
                cpu: 3
                memory: 2500Mi