---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: auth0-signing-key
  namespace: auth0-system
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)

