apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kapp.k14s.io/change-group: "postgres-operator"
  name: pg-operator-install-cluster-admin-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: "postgres-operator"
  name: pg-operator-install-cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pg-operator-install-cluster-admin-role
subjects:
  - kind: ServiceAccount
    name: pg-operator-install-sa
    namespace: vmware-postgres-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: "postgres-operator"
  name: pg-operator-install-sa
  namespace: vmware-postgres-operator