apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: registry-credentials
  namespace: vmware-postgres-operator
  annotations:
    kapp.k14s.io/change-group: "postgres-operator"
spec:
  fromNamespace: tap-install