---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: packages-gitops-repo
  namespace: kustomize-fun
spec:
  url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
  ignore: |
    !.git
  interval: 30s
  ref:
    branch: main
  timeout: 60s
  secretRef:
    name: tenant-gitops-ssh
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: carvel-workload-kustomize-packages
  namespace: kustomize-fun
spec:
  sourceRef:
    kind: GitRepository
    name: packages-gitops-repo
    namespace: kustomize-fun
  path: "./packages/carvel-workload-kustomize.kustomize-fun.cssa.vmware.com/packages"
  interval: 5m
  timeout: 5m
  prune: true
  wait: true