apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canary
rules:
- apiGroups: ["flagger.app", "apiextensions.k8s.io/v1"]
  resources: ["canaries", "customresourcedefinitions"]
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection