apiVersion: v1
kind: Secret
metadata:
  name: ootb-cluster-delivery-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-cluster-delivery-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
        
    #@overlay/match by=overlay.subset({"apiVersion": "carto.run/v1alpha1", "kind": "ClusterDelivery","metadata":{"name":"delivery-basic"}}), expects="1+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/append
      - name: test-and-notify
        templateRef:
          kind: ClusterTemplate
          name: test-and-notify-template
        sources:
        - resource: deployer
          name: source