---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: workload-image-policy
spec:
  mode: enforce
  images:
  - glob: cxscssa.azurecr.io/tap-build/workloads/app-golang-kaniko*
  match:
  - group: workload
    resource: pods
    version: v1
    selector:
      matchLabels:
        carto.run/workload-name: app-golang-kaniko
  authorities:
  - static:
      action: pass
  - key:
      secretRef:
        name: cosign