---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: workload-image-policy
spec:
  mode: enforce
  images:
  - glob: cxscssa.azurecr.io/tap-build/workloads/tanzu-java-web-app-1-7-azure*
  match:
  - group: workload
    resource: pods
    version: v1
    selector:
      matchLabels:
        carto.run/workload-name: tanzu-java-web-app-1-7-azure
  authorities:
  - static:
      action: fail
  - key:
      secretRef:
        name: cosign