---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: warn
spec:
  images:
  - glob: cxscssa.azurecr.io/tap-build/workloads/*
  authorities:
  - key:
      secretRef:
        name: cosign
  - static:
    action: pass