apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: cosign
    creationPolicy: Owner
    template:
      data:
        cosign.key: "{{ .cosignkey | b64dec }}"
        cosign.password: "{{ .cosignpassword }}"
        cosign.pub: "{{ .cosignpub | b64dec }}"

  data:
  - secretKey: cosignkey
    remoteRef:
      key: cosignkey
  - secretKey: cosignpassword
    remoteRef:
      key: cosignpassword
  - secretKey: cosignpub
    remoteRef:
      key: cosignpub
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cosign
  namespace: tap-install
spec:
  toNamespaces: 
    - cosign-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: cosign
  namespace: cosign-system
spec:
  fromNamespace: tap-install