apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deliverables
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-azure-deliverable-config-repo.git
      ref: origin/main
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            gitops:
              branch: main
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-override-ownership-of-existing-resources=true
      - --dangerous-allow-empty-list-of-resources=true
      - --diff-changes=true