---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tap-repository-1-6-8
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: cxscssa.azurecr.io/tap-1-6-8/tap-packages:1.6.8

---
apiVersion: v1
kind: Secret
metadata:
  name: fluxcd-overlay
  namespace: tap-install
stringData:
  overlay-tap-pkgi.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "PackageInstall", "metadata": {"name": "fluxcd-source-controller"}}), expects="0+"
    ---
    spec:
      packageRef:
        refName: fluxcd.source.controller.tanzu.vmware.com
        versionSelection:
          constraints: "0.36.1+tanzu.2"
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        packaging.carvel.dev/downgradable: ""
