apiVersion: v1
kind: Secret
metadata:
  name: fluxcd-source-overlay
  namespace: tap-install
stringData:
  fluxcd-source-overlay.yaml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"fluxcd-source-controller", "namespace": "flux-system"}}), expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: manager
            resources:
              limits:
                cpu: "4"
                memory: "4Gi"
              requests:
                cpu: "2"
                memory: "2Gi"
            args:
            - --concurrent=30
            - --requeue-dependency=5s
            - --artifact-retention-records 20
            - --artifact-retention-ttl 5m0s