---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
 name: tanzu-java-web-package
 namespace: mae
spec:
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-azure-workload-config-repo.git
      ref: origin/main
      secretRef: 
        name: tap-install-gitops-ssh
      subPath: packages/tanzu-java-web-package.mae.cssa.vmware.com/packages
  template:
  - ytt: {}
  
  deploy:
  - kapp:
      intoNs: mae
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]