apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-values
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: run
          ceip_policy_disclosed: true

          shared:
            ingress_domain: run.cssa.tapsme.org
            ingress_issuer: letsencrypt-production

          amr:
            observer:
              location: |
                labels:
                - key: env
                  value: test
              cloudevent_handler:
                endpoint: "https://amr-cloudevent-handler.view.cssa.tapsme.org"
                liveness_period_seconds: 10
              auth:
                kubernetes_service_accounts:
                  enable: true
              ca_cert_data: |
                -----BEGIN CERTIFICATE-----
                MIIFITCCBAmgAwIBAgISBARKpyLDsqw9W/cSVKxxbvw7MA0GCSqGSIb3DQEBCwUA
                MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
                EwJSMzAeFw0yNDAyMDIxNzQyMTNaFw0yNDA1MDIxNzQyMTJaMDYxNDAyBgNVBAMT
                K2Ftci1jbG91ZGV2ZW50LWhhbmRsZXIudmlldy5jc3NhLnRhcHNtZS5vcmcwggEi
                MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCx8Nl3eh+quzD+8sZSzrofWSkB
                Bfb3pT986DB41+8JI6DdPyuf5N69CyZTmM19tfwYaO1GxtNo1luimUlaTUS10fjq
                oDgqx3Ucp0KQ+XCfeUdVMJHhWAL2i8pJAdFwxP9u99Hw5ts8ywytsdODVT2xCVEx
                ZAzuZVxn2Jvt1Jv2atsSrI+I+6v79AiX7D8t8I6CKqWQn8ql0WmNZHIRZk+FTC9p
                /tFAvIBnjArN4Dvgk3q/Z560y5aZZnza6QvkbmNYVZzVH3XLDtue5V9rQvHJVGaW
                Npgv0mvVmFYhIp7QQLoWI8hWLHGod64qI+1grgHz6PzKi5GyHtqueTlfNspDAgMB
                AAGjggIrMIICJzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
                CCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFCRDSTzNykqm2UFUBE/y
                DPZQVAF9MB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUF
                BwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsG
                AQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMDYGA1UdEQQvMC2CK2Ftci1j
                bG91ZGV2ZW50LWhhbmRsZXIudmlldy5jc3NhLnRhcHNtZS5vcmcwEwYDVR0gBAww
                CjAIBgZngQwBAgEwggECBgorBgEEAdZ5AgQCBIHzBIHwAO4AdQBIsONr2qZHNA/l
                agL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAY1rIOMJAAAEAwBGMEQCIHIpTStJPdpp
                XrZz5JbGPas/dV6v6rVqhpbuuYgpyWhyAiBUHpVmHST/NVCxzvDsQs/eK+5S9/2z
                5RBq7bbptU+X2wB1AKLiv9Ye3i8vB6DWTm03p9xlQ7DGtS6i2reK+Jpt9RfYAAAB
                jWsg4ykAAAQDAEYwRAIgQYYJ2XLLlfXz4X0Gi5LzwDoepuVcg3OJ0s9arUMZ2BIC
                IHfZouIORDZK22HQ6Hwu7rfvnI7DoPW4k3yYW09Cjl3aMA0GCSqGSIb3DQEBCwUA
                A4IBAQBK6YUccRijTXbl6N+sRHrtn+A2JsXZtKDqgABUWbf3EyivSANZkU1rvida
                6HcyItWshYI5shVNT50gHyw8nhdKDzkDtOfd+ut9uxaYSvaPNdYumPdh/4xs5eOA
                CtxvGHeWm6knwDnGUcJitPtv15AUEojToUX8+A+7le1NWLuuXLSV0RKFato4T9iy
                LTNcLWfpMxB5ZoFqipu18BPf1fYZEEmqRiIm1sOTx2gslE2X4DgRQ/Ix6aD24cfY
                D6/WFZ8tykdAe1/jWe1E+Y4s1eFMiR9WueQwxrptMRqWhxLC/2QqTRkjgw2deLYx
                tU6xGGa541tjENl9J37jeRu9f9d7
                -----END CERTIFICATE-----
                -----BEGIN CERTIFICATE-----
                MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
                TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
                cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
                WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
                RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
                AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
                R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
                sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
                NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
                Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
                /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
                AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
                Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
                FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
                AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
                Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
                gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
                PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
                ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
                CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
                lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
                avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
                yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
                yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
                hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
                HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
                MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
                nLRbwHOoq7hHwg==
                -----END CERTIFICATE-----
                -----BEGIN CERTIFICATE-----
                MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
                MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
                DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
                TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
                cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
                AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
                ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
                wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
                LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
                4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
                bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
                sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
                Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
                FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
                SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
                PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
                TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
                SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
                c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
                +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
                ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
                b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
                U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
                MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
                5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
                9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
                WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
                he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
                Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
                -----END CERTIFICATE-----
        
          supply_chain: basic

          contour:
            envoy:
              logLevel: debug
              service:
                type: LoadBalancer   

          namespace_provisioner:
            controller: false
            default_parameters:
              supply_chain_service_account:
                secrets:
                - tap-registry
                - tenant-gitops-ssh
                - git-credentials
                - oci-store
            additional_sources:
            - git:
                url: ssh://git@github.com/Mpluya/tap-namespaces-azure
                ref: origin/main
                subPath: additional-resources
                secretRef:
                  name: tap-install-gitops-ssh-too
                  namespace: tap-install
                  create_export: true
              path: _ytt_lib/custom-resources
            - git:
                url: ssh://git@github.com/Mpluya/tap-namespaces-azure
                ref: origin/main
                subPath: additional-resources-run
                secretRef:
                  name: tap-install-gitops-ssh-too
                  namespace: tap-install
              path: _ytt_lib/custom-resources-run 
            gitops_install:
              ref: origin/main
              subPath: ns-provisioner-base
              url: ssh://git@github.com/Mpluya/tap-namespaces-azure
              secretRef:
                name: tap-install-gitops-ssh
                namespace: tap-install
            overlay_secrets:
            - name: workload-git-ssh-overlay
              namespace: tap-install
              create_export: true

          appliveview_connector:
            backend:
              ingressEnabled: true
              host: appliveview.view.cssa.tapsme.org
            connector:
              deployment:
                enabled: true
                replicas: 1

          api_auto_registration:
            tap_gui_url: "https://tap-gui.view.cssa.tapsme.org"
            cluster_name: run

          crossplane:
            orphan_resources: false
              
          policy:
            no_match_policy: warn

          package_overlays:
          - name: ootb-delivery-basic
            secrets: 
            - name: ootb-cluster-delivery-overlay
          - name: ootb-templates
            secrets:
            - name: ootb-templates-overlay
            - name: tap-scale-overlays
          - name: fluxcd-source-controller
            secrets:
            - name: tap-scale-overlays
          - name: cnrs
            secrets:
            - name: update-queue-sidecar-overlay-secret

          # excluded_packages:
          # - fluxcd-source-controller.tanzu.vmware.com

  data:
  - secretKey: githubclientsecret
    remoteRef:
      key: githubclientsecret
