apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: tap-values
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: run
          ceip_policy_disclosed: true

          shared:
            ingress_domain: run.cssa.tapsme.org
            ingress_issuer: letsencrypt-production

          supply_chain: basic

          contour:
            envoy:
              service:
                type: LoadBalancer   

          namespace_provisioner:
            controller: false
            additional_sources:
            - git:
                url: ssh://git@github.com/Mpluya/tap-namespaces-azure
                ref: origin/main
                subPath: additional-resources
                secretRef:
                  name: tap-install-gitops-ssh-too
                  namespace: tap-install
                  create_export: true
              path: _ytt_lib/custom-resources
            gitops_install:
              ref: origin/main
              subPath: ns
              url: ssh://git@github.com/Mpluya/tap-namespaces-azure
              secretRef:
                name: tap-install-gitops-ssh
                namespace: tap-install
            overlay_secrets:
            - name: workload-git-ssh-overlay
              namespace: tap-install
              create_export: true

          appliveview_connector:
            backend:
              ingressEnabled: true
              host: appliveview.view.cssa.tapsme.org

          api_auto_registration:
            tap_gui_url: "https://tap-gui.view.cssa.tapsme.org"
            cluster_name: run
  data:
  - secretKey: githubclientsecret
    remoteRef:
      key: githubclientsecret
