apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pg-metadata-store
  namespace: postgres-metadata-store
  annotations:
    kapp.k14s.io/change-group: "postgres-metadata-store"
    kapp.k14s.io/change-rule.create-order-0: "upsert after upserting postgres-operator-package"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting postgres-operator-package"
spec:
  serviceType: LoadBalancer
  readOnlyServiceType: LoadBalancer
  storageClassName: default
  storageSize: 250M
  highAvailability:
    enabled: true
    readReplicas: 1
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: tap-registry
  pgConfig:
    dbname: metadata-store
    username: pgadmin
    appUser: pgappuser
    readOnlyUser: pgrouser
    readWriteUser: pgrwuser
  customConfig:
    pghba:
      name: pg-metadata-store-hba-configmap