apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-post-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install-azure
      ref: origin/main
      subPath: run-prod-post-packaging
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt: {}

  deploy:
  - kapp:
      rawOptions:
      - --diff-changes=true
      - --wait=false