apiVersion: v1
kind: Secret
metadata:
  name: tap-pkg-overlay-secret
  namespace: tap-install
stringData:
  overlay-tap-pkgi.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"PackageInstall","metadata":{"namespace":"tap-install"}}),expects="1+"
    ---
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.98: tolerations-overlay-secret