apiVersion: v1
kind: Secret
metadata:
  name: tolerations-overlay-secret
  namespace: tap-install
stringData:
  tolerations-overlay-secret.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@ def match_namespace():
    kind: Namespace
    #@ end

    #@overlay/match by=overlay.subset(match_namespace()), expects="0+"
    ---
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "effect": "NoSchedule", "key": "usage", "value": "tap"}]'