apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secretgenpasswordmaintainer
  namespace: crossplane-system
rules:
- apiGroups:
  - secretgen.k14s.io
  resources:
  - passwords
  verbs:
  - get
  - list
  - watch
  - create
  - update