apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secretgenreader
  namespace: crossplane-system
rules:
- apiGroups:
  - secretgen.k14s.io
  resources:
  - passwords
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-kubernetes-rb
  namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secretgenreader
subjects:
- kind: ServiceAccount
  name: provider-kubernetes
  namespace: crossplane-system